(()=>{
const C=APP_CONFIG,$=id=>document.getElementById(id);
let token=localStorage.rcvToken||'',student=JSON.parse(localStorage.rcvStudent||'null'),game=null,q=null,answered=-1,offset=0,timer=null,poll=null,joined=localStorage.rcvJoined==='1';
function api(action,p={}){return new Promise((ok,no)=>{const cb='rcv_'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script');window[cb]=x=>{delete window[cb];s.remove();x.success?ok(x):no(Error(x.error||'Lỗi máy chủ'))};s.onerror=()=>{delete window[cb];s.remove();no(Error('Không kết nối được máy chủ'))};s.src=C.API_URL+'?'+new URLSearchParams({action,callback:cb,...p});document.body.appendChild(s)})}
function now(){return Date.now()+offset} function show(x){$(x).classList.remove('hidden')} function hide(x){$(x).classList.add('hidden')}
async function sync(){try{const t=Date.now(),x=await api('state',{token}),t2=Date.now();offset=x.serverTime-Math.round((t+t2)/2);game=x.game;q=x.question;if(typeof x.joined==='boolean'){joined=x.joined;if(joined)localStorage.rcvJoined='1';else localStorage.removeItem('rcvJoined')}render()}catch(e){if($('notice'))$('notice').textContent=e.message}}
function render(){if(!student)return;$('badge').textContent=student.fullName+' • '+student.className;$('alive').textContent=game.aliveCount;
 if(game.status==='FINISHED'){hide('login');hide('join');hide('wait');hide('quiz');show('finish');stop();loadResult();return}
 if(!joined){hide('wait');hide('quiz');hide('finish');show('join');return}
 if(game.status!=='RUNNING'){hide('join');hide('quiz');show('wait');$('readyCount').textContent=String(game.readyCount||0);stop();return}
 hide('join');hide('wait');show('quiz');if(q)renderQ();clock();}
function renderQ(){const changed=q.number!==answered;$('qn').textContent=String(q.number).padStart(2,'0');$('question').textContent=q.question;$('answers').innerHTML=Object.entries(q.options).map(([k,v])=>`<button data-a="${k}" ${answered===q.number?'disabled':''}><b>${k}</b><span>${esc(v)}</span></button>`).join('');document.querySelectorAll('#answers button').forEach(b=>{b.onclick=()=>answer(b.dataset.a);if(answered===q.number&&b.dataset.a===window.rcvLastAnswer)b.classList.add('selected')});$('bar').style.width=((q.number-1)/game.totalQuestions*100)+'%';if(changed)$('notice').textContent='Chọn một đáp án.';}
function clock(){stop();const tick=()=>{if(!game.endsAt)return;const left=Math.max(0,game.endsAt-now());$('timer').textContent=Math.ceil(left/1000);if(left<=0){lock('HẾT THỜI GIAN');return}timer=requestAnimationFrame(tick)};tick()}
function stop(){if(timer)cancelAnimationFrame(timer);timer=null} function lock(m){document.querySelectorAll('#answers button').forEach(b=>b.disabled=true);$('notice').textContent=m}
async function answer(a){if(!game||game.status!=='RUNNING'||answered===game.currentQuestion)return;answered=game.currentQuestion;window.rcvLastAnswer=a;document.querySelector(`[data-a="${a}"]`)?.classList.add('selected');lock('Đang ghi nhận đáp án...');try{const x=await api('answer',{token,answer:a});$('notice').textContent=x.correct?'✓ ĐÚNG — Đã ghi nhận!':'Đã ghi nhận đáp án.'}catch(e){answered=-1;$('notice').textContent=e.message}}
async function joinRoom(){if(!token)return;$('joinMsg').textContent='Đang vào phòng thi...';try{await api('join',{token});joined=true;localStorage.rcvJoined='1';$('joinMsg').textContent='Đã vào phòng thi.';hide('join');show('wait');sync()}catch(e){$('joinMsg').textContent=e.message}}
async function loadResult(){try{const x=await api('results'),m=x.results.find(r=>r.studentId===student.studentId);if(m)$('mine').innerHTML=`${esc(m.fullName)}<br><b>Điểm: ${m.score}</b> • Đúng: ${m.correct}<br>${esc(m.status)}`}catch(e){}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('joinBtn').onclick=joinRoom;
$('form').onsubmit=async e=>{e.preventDefault();$('msg').textContent='Đang xác thực...';try{const x=await api('login',{username:$('user').value.trim(),password:$('pass').value});token=x.token;student=x.student;joined=false;localStorage.rcvToken=token;localStorage.rcvStudent=JSON.stringify(student);localStorage.removeItem('rcvJoined');hide('login');show('join');sync();if(poll)clearInterval(poll);poll=setInterval(sync,C.POLL_MS||1200)}catch(e){$('msg').textContent=e.message}};
if(token&&student){hide('login');if(joined)show('wait');else show('join');sync();poll=setInterval(sync,C.POLL_MS||1200)}
})();